CREATE DATABASE ${POSTGRES_DB};
CREATE ROLE ${POSTGRES_USER} WITH LOGIN PASSWORD :'POSTGRES_PASSWORD';
GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_USER};
ALTER USER ${POSTGRES_USER} WITH SUPERUSER;

-- Create keycloak database and user
CREATE DATABASE keycloak;
CREATE ROLE keycloak WITH LOGIN PASSWORD :'KEYCLOAK_PASSWORD';
GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak;

-- Grant superuser privileges to postgres user (if needed)
ALTER USER :POSTGRES_USER WITH SUPERUSER;