// Code generated by options-gen. DO NOT EDIT.
package keycloakclient

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	basePath string,
	realm string,
	clientID string,
	clientSecret string,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	o.basePath = basePath

	o.realm = realm

	o.clientID = clientID

	o.clientSecret = clientSecret

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithUsername(opt string) OptOptionsSetter {
	return func(o *Options) {
		o.username = opt

	}
}

func WithPassword(opt string) OptOptionsSetter {
	return func(o *Options) {
		o.password = opt

	}
}

func WithDebugMode(opt bool) OptOptionsSetter {
	return func(o *Options) {
		o.debugMode = opt

	}
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("basePath", _validate_Options_basePath(o)))
	return errs.AsError()
}

func _validate_Options_basePath(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.basePath, "required,url"); err != nil {
		return fmt461e464ebed9.Errorf("field `basePath` did not pass the test: %w", err)
	}
	return nil
}
