// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mock_middlewares is a generated GoMock package.
package mock_middlewares

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	keycloakclient "github.com/Fisher-Development/woman-app-backend/internal/clients/keycloak"
)

// MockKeycloakClient is a mock of KeycloakClient interface.
type MockKeycloakClient struct {
	ctrl     *gomock.Controller
	recorder *MockKeycloakClientMockRecorder
}

// MockKeycloakClientMockRecorder is the mock recorder for MockKeycloakClient.
type MockKeycloakClientMockRecorder struct {
	mock *MockKeycloakClient
}

// NewMockKeycloakClient creates a new mock instance.
func NewMockKeycloakClient(ctrl *gomock.Controller) *MockKeycloakClient {
	mock := &MockKeycloakClient{ctrl: ctrl}
	mock.recorder = &MockKeycloakClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeycloakClient) EXPECT() *MockKeycloakClientMockRecorder {
	return m.recorder
}

// IntrospectToken mocks base method.
func (m *MockKeycloakClient) IntrospectToken(ctx context.Context, token string) (*keycloakclient.IntrospectTokenResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntrospectToken", ctx, token)
	ret0, _ := ret[0].(*keycloakclient.IntrospectTokenResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IntrospectToken indicates an expected call of IntrospectToken.
func (mr *MockKeycloakClientMockRecorder) IntrospectToken(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntrospectToken", reflect.TypeOf((*MockKeycloakClient)(nil).IntrospectToken), ctx, token)
}
